env: "local"
server:
  host: "localhost"
  port: "8080"
  read_timeout: 5m
  write_timeout: 5m

postgres:
  host: "localhost"
  port: "5432"
  username: "mikance"
  password: "16777216"
  db_name: "todoapp"
  ssl_mode: "disable"